{{- if and .Values.openSearch.auth.enabled (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-prepper.fullname" . }}-opensearch-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: {{ .Values.openSearch.auth.username | default "" | b64enc | quote }}
  password: {{ .Values.openSearch.auth.password | default "" | b64enc | quote }}
{{- end }}
