apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-prepper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-source
      port: {{ .Values.service.httpSourcePort }}
      targetPort: http-source
      protocol: TCP
    - name: otel-trace-grpc
      port: {{ .Values.service.otelTraceSourcePort }}
      targetPort: otel-trace-grpc
      protocol: TCP
    - name: server
      port: {{ .Values.service.serverPort }}
      targetPort: server
      protocol: TCP
  selector:
    {{- include "data-prepper.selectorLabels" . | nindent 4 }}
